[package]
name = "nobscount"
version = "1.0.0"
edition = "2024"

[dependencies]
image = {version = "0.25.6", default-features = false, features = ["png"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.21", features = ["parse"] }
