[package]
name = "nobscount"
version = "1.2.3"
edition = "2024"

[dependencies]
ctrlc = "3.4.7"
nix = { version = "0.30.1", features = ["signal", "socket"] }
regex = "1.11.1"
toml = { version = "0.8.21", features = ["parse"] }
